# .goreleaser.yml

project_name: backubrr
project_tagline: A backup utility

builds:
- main: backubrr.go
  ldflags: -s -w
  goos:
  - linux
  - darwin
  goarch:
  - amd64

#archive:
#  replacements:
#    HOME: ~

env:
  - CGO_ENABLED=0

release:
  github:
    owner: s0up4200
    name: backubrr
    token: $MY_SECRET
    draft: true
    prerelease: true

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

checksum:
  name_template: 'checksums.txt'

hooks:
  post:
    - go version
    - echo 'Deployed successfully!'
